CREATE TABLE public.driver (
	available bool NULL,
	id_driver int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	phone_number varchar(255) NULL,
	vehicle varchar(255) NULL,
	CONSTRAINT driver_pkey PRIMARY KEY (id_driver)
);

CREATE TABLE public.delivery (
	estimated_delivery_time timestamp(6) NULL,
	id_delivery int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_driver int8 NULL,
	destination_address varchar(255) NULL,
	status varchar(255) NULL,
	CONSTRAINT delivery_pkey PRIMARY KEY (id_delivery),
	CONSTRAINT delivery_driver FOREIGN KEY (id_driver) REFERENCES public.driver(id_driver)
);

CREATE TABLE public."location" (
	latitude float8 NOT NULL,
	longitude float8 NOT NULL,
	id_delivery int8 NULL,
	id_location int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"timestamp" timestamp(6) NULL,
	CONSTRAINT location_pkey PRIMARY KEY (id_location),
	CONSTRAINT location_delivery FOREIGN KEY (id_delivery) REFERENCES public.delivery(id_delivery)
);

-- Inserts para a tabela driver
INSERT INTO public.driver (available, "name", phone_number, vehicle) 
VALUES
  (TRUE, 'Carlos Silva', '999888777', 'Carro - Honda Civic'),
  (FALSE, 'Ana Oliveira', '988777666', 'Moto - Yamaha XJ6'),
  (TRUE, 'Roberto Costa', '977666555', 'Carro - Ford Focus'),
  (TRUE, 'Luciana Pereira', '966555444', 'Carro - Toyota Corolla'),
  (FALSE, 'Pedro Souza', '955444333', 'Moto - Ducati Monster');

-- Inserts para a tabela delivery
INSERT INTO public.delivery (estimated_delivery_time, id_driver, destination_address, status) 
VALUES
  ('2024-11-23 10:00:00', 1, 'Rua das Flores, 123', 'Em andamento'),
  ('2024-11-23 12:30:00', 2, 'Av. Brasil, 456', 'Aguardando coleta'),
  ('2024-11-23 14:15:00', 3, 'Rua São Paulo, 789', 'Entregue'),
  ('2024-11-23 16:45:00', 4, 'Praça Central, 101', 'Em andamento'),
  ('2024-11-23 18:00:00', 5, 'Rua Rio de Janeiro, 202', 'Cancelada');

-- Inserts para a tabela location
INSERT INTO public."location" (latitude, longitude, id_delivery, "timestamp") 
VALUES
  (-23.550520, -46.633308, 1, '2024-11-23 09:45:00'),
  (-23.555440, -46.633270, 2, '2024-11-23 12:00:00'),
  (-23.558220, -46.625810, 3, '2024-11-23 14:00:00'),
  (-23.559870, -46.627350, 4, '2024-11-23 16:30:00'),
  (-23.560720, -46.629480, 5, '2024-11-23 17:45:00');
