services:
  java_db:
    container_name: java_db
    image: postgres

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: api
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - java_db
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker